language: node_js

node_js:
   - "8"

services:
   - mongodb

before_script:
   - sleep 4
   - mongo admin --eval "db.createUser({user:'root',pwd:'root',roles:['root']});"
   - sleep 4
   - mongo admin -u "root" -p "root" --authenticationDatabase "admin" --eval "db.createUser({user:'db-admin-kunlun-test',pwd:'abc123',roles:['dbAdminAnyDatabase']});"
   - mongo admin -u "root" -p "root" --authenticationDatabase "admin" --eval "db.createUser({user:'read-write-kunlun-test',pwd:'abc123',roles:['readWriteAnyDatabase']});"
   - sleep 4

cache:
   directories:
      - node_modules

sudo: false

addons:
   apt:
      sources:
         - mongodb-3.0-precise
      packages:
         - mongodb-org-server
         - mongodb-org-shell

notifications:
   email: false

branches:
   only:
      - master
